# Generated by Django 3.1.3 on 2021-11-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_num', models.IntegerField(verbose_name='챕터 번호')),
                ('content', models.TextField(blank=True, null=True, verbose_name='보조내용')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('limit', models.IntegerField(verbose_name='글자수')),
                ('q_type', models.IntegerField(verbose_name='질문 타입')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.chapter', verbose_name='해당 챕터')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=900, verbose_name='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.chapter', verbose_name='해당 챕터')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesscode', verbose_name='시리얼키')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.question', verbose_name='해당 질문')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_num', models.IntegerField(verbose_name='주소 개수')),
                ('c_progress', models.IntegerField(verbose_name='챕터 진행')),
                ('q_progress', models.IntegerField(verbose_name='질문 진행')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesscode', verbose_name='시리얼키')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='선택지')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.chapter', verbose_name='해당 챕터')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.question', verbose_name='해당 질문')),
            ],
        ),
    ]
