# Generated by Django 3.1.3 on 2021-11-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='code',
        ),
        migrations.RemoveField(
            model_name='response',
            name='code',
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='유저', to=settings.AUTH_USER_MODEL),
        ),
    ]
