# Generated by Django 3.1.3 on 2021-11-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0002_auto_20211110_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='star',
            field=models.BooleanField(default=False, verbose_name='별표'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
