# Generated by Django 3.1.3 on 2021-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_auto_20211111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='글자수'),
        ),
    ]
