# Generated by Django 3.1.3 on 2021-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_auto_20211111_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.CharField(max_length=900, verbose_name='답변 내용'),
        ),
    ]
