# Generated by Django 3.1.3 on 2021-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_auto_20211111_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='챕터 제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='보조 내용'),
        ),
    ]
