# Generated by Django 3.1.3 on 2021-11-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0006_auto_20211111_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='c_progress',
            field=models.IntegerField(default=1, verbose_name='챕터 진행'),
        ),
        migrations.AlterField(
            model_name='info',
            name='q_progress',
            field=models.IntegerField(default=1, verbose_name='질문 진행'),
        ),
    ]
