# Generated by Django 3.1.3 on 2021-11-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0007_auto_20211111_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='유저'),
            preserve_default=False,
        ),
    ]
