# Generated by Django 3.1.3 on 2021-11-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0008_auto_20211111_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastHello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='마지막인사 이름')),
                ('contact', models.CharField(max_length=20, verbose_name='마지막인사 연락처')),
            ],
        ),
    ]
