# Generated by Django 3.1.3 on 2021-11-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0009_lasthello'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasthello',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talk.chapter', verbose_name='해당 챕터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lasthello',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talk.question', verbose_name='해당 질문'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lasthello',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
