# Generated by Django 3.1.3 on 2021-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0010_auto_20211112_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(default=0, verbose_name='질문 타입'),
        ),
    ]
