# Generated by Django 3.1.3 on 2021-11-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0011_auto_20211113_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='질문 내용'),
        ),
    ]
