# Generated by Django 3.1.3 on 2021-11-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('birth', models.CharField(max_length=8, verbose_name='생년월일')),
                ('l_food1', models.CharField(max_length=10, verbose_name='좋아하는 음식1')),
                ('l_food2', models.CharField(max_length=10, verbose_name='좋아하는 음식2')),
                ('l_food3', models.CharField(max_length=10, verbose_name='좋아하는 음식3')),
                ('h_food1', models.CharField(max_length=10, verbose_name='싫어하는 음식1')),
                ('h_food2', models.CharField(max_length=10, verbose_name='싫어하는 음식2')),
                ('h_food3', models.CharField(max_length=10, verbose_name='싫어하는 음식3')),
                ('good', models.CharField(max_length=20, verbose_name='장점')),
                ('bad', models.CharField(max_length=20, verbose_name='단점')),
                ('hobby', models.CharField(max_length=20, verbose_name='취미')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesscode', verbose_name='시리얼키')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='수령인')),
                ('phone', models.CharField(max_length=11, verbose_name='전화번호')),
                ('postal', models.CharField(max_length=5, verbose_name='우편번호')),
                ('addy', models.CharField(max_length=100, verbose_name='주소')),
                ('is_other', models.BooleanField(default=True, verbose_name='타인?')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesscode', verbose_name='시리얼키')),
            ],
        ),
    ]
